### ISSUE TITLE
When I select a day, it executes the functions twice. 

### ISSUE THREAD

**Issue by londonbridges13** [CVCalendar/CVCalendar#148]
For example:

The didSelectDayView, inside it has 
        print("(calendarView.presentedDate.commonDescription) is selected!")

Well when I select a Date it does this Twice, how can I make it execute only once?

**Comment by elsesiy** [comment]
@londonbridges13 Currently the func `didSelectDayView` is called twice because it's mistakenly being called twice during the init and later on too, if you switch on a different day it's been triggered twice because of the TouchController-Event and the CVCalendarViewAnimator.

You can't do much, but we're working on it...sorry!

**Comment by cre8it** [comment]
any fix on that?

**Comment by keval9999** [comment]
Try this 
in CVcalendarViewAnimator.swift  comment folling  three line in animateselectionondayview() function

 // let selectionAnimation = delegate.selectionAnimation()

// selectionAnimation(dayView) { [unowned dayView] completion in
      //      dayView.calendarView.delegate?.didSelectDayView?(dayView, animationDidFinish: completion  
       // }

its working ..... try this

**Comment by jgutierrez11** [comment]
@keval9999  thanks, but now the animation doesn't appear.
