### ISSUE TITLE
Circle Size of Selected Day

### ISSUE THREAD

**Issue by rhenz** [CVCalendar/CVCalendar#186]
Is there any way to adjust the size of the circle selected state?

**Comment by adamdahan** [comment]
Useless library amigo. 75 issues with nobody responding to any issues.

**Comment by elsesiy** [comment]
@rhenz Please take a look at CVAuxiliaryView. The radius is calculated from the frame of the view, but as of now there's no option to specify it directly.

@adamdahan Thanks for being so positive. Me and @Mozharovsky are maintaining the project in our spare time, hence we spend as much time as possible to help you guys solving your issues and in addition implement new features. It's natural that due to time constraints a certain technical debt occurs, but don't be a dick. No one asked you to use our software, so either you maintain a certain level of friendliness or go and build your own library.
