### ISSUE TITLE
About shouldAutoSelectDayOnMonthChange and Today button

### ISSUE THREAD

**Issue by mehdi-shiba** [CVCalendar/CVCalendar#196]
Thank you to everyone involved for this fantastic library.
I was playing with the demo, and found something weird when implementing:

`func shouldAutoSelectDayOnMonthChange() -> Bool {
        return false
    }`
After adding it, the Today button (the little Clock icon at the top-right of screen) would no longer take me back to current day. Any idea why?

**Comment by elsesiy** [comment]
@mehdi-shiba Thanks for using our library and providing feedback!
So basically the problem is that you say don't selected the current date if you return false in `func shouldAutoSelectDayOnMonthChange() -> Bool { return false }` and then still want it to be selected...
The clock uses the convenience api `func togglePresentedDate(date: NSDate)` to take you back to the current date. The implementation of it checks whether the optional `selectedDayView.date` is available prior to perform the toggling, which you clearly stated to be: "No I don't want any selection to be performed if I change the month"...

**Comment by Incyc** [comment]
I too ran into this problem, and I don't believe `togglePresentedDate:` should assume that day selection is required. I am using the calendar purely as a view-only calendar with no support for selection of dates. In this use case, I would still like to be able to go back to the current date without implicitly making any selections. I may try to work on adding this as a PR if others also think this is will be a useful use case.

**Comment by elsesiy** [comment]
@Incyc Sounds valid to me, looking forward to that PR.

**Comment by pavelhiq** [comment]
Sounds absolutely reasonable for me, have a similar problem that a call to _toggleViewWithDate(date)_ seems to be ignored if _shouldAutoSelectDayOnMonthChange()_ returns _false_...

**Comment by danielbmarques** [comment]
Yes, there are plenty of problems with `shouldAutoSelectDayOnMonthChange()`. If I return false the current date won't be automatically selected either, and I want it to be selected at first, I just don't want that selection to change when the user scrolls to another month. The way I see it the selection of the current date should be independent from the automatic selection that happens on month changes, and that would fix all the problems mentioned here.
