### ISSUE TITLE
Remove localisation for months & days

### ISSUE THREAD

**Issue by coanag** [CVCalendar/CVCalendar#200]
Im not able to remove localisation for days and months. Just want all to be in English.
Any guidance appreciated.

**Comment by elsesiy** [comment]
@coanag Why would you wanna do that? Please explain what you've tried so far and how your setup looks like, i.e. does your app support multiple languages, etc.

**Comment by coanag** [comment]
My app is English only.
Users with other locales, seeing calendar months and days in local languages.
In my case localization doesn't has a purpose.

**Comment by elsesiy** [comment]
@coanag Yes they do, since if the user's phone has a different region/language set, they usually want to see all information in the region-specific notation. At the moment, there's no possibility to manually set a region, so the date is being localized. 

@Mozharovsky What do you think? Shall we consider this issue for the next big release?

**Comment by Izakc** [comment]
Yes please :D

**Comment by akabab** [comment]
+1! is there a way to force it to english for now ?

**Comment by eschmitt-Ikky** [comment]
+1
Perhaps allow an override for the day textfield content. We use in-app dynamic localisation. So, not being able to override the text causes issues.

**Comment by hastoukopsaro** [comment]
@eschmitt-Ikky has a point there... Apps might use different in-app language than the users phone.

+1
