### ISSUE TITLE
How to get the weekday in the calendar & How to customize the selection of date?

### ISSUE THREAD

**Issue by GABHISEKBUNTY** [CVCalendar/CVCalendar#230]
1)I am implementing CVCalendar to create a custom calendar but I could not get exactly how to get the current week day so as to display the day selected. 

2)How can I customize the selection colour ?

**Comment by patchthecode** [comment]
found a solution?

**Comment by GABHISEKBUNTY** [comment]
No I didn't get but try using FSCalendar. Its a bit more handy & easy to customise.

**Comment by patchthecode** [comment]
Ok. I looked at FSCalendar, but it was too large. While it does makes things customisable, i wanted one that could customize the way i wanted. Instead of giving me a list of options to choose from. So i created my own. JTAppleCalendar. But cool, i thought you got a solution for this one. Thanks for the response

**Comment by GABHISEKBUNTY** [comment]
So do u have ur source code on gitHub ?

**Comment by zuaaef** [comment]
Yea, its on github. But its even easier if you use CocoaPods --> https://cocoapods.org/pods/JTAppleCalendar

**Comment by patchthecode** [comment]
lol yea. what zuaaef said.
