### ISSUE TITLE
Selecting a day in different month is not selected properly

### ISSUE THREAD

**Issue by bjaskj** [CVCalendar/CVCalendar#243]
Missbehaviour 1:
If I view March 2016 and click on February 28, it does not go to February and select 28th, but rather selects February 1st.

Missbehaviour 2:
Also if I am in February 2016 and select March 4th, it selects March 7th (the current date).

**Comment by DennisH511** [comment]
By default when shouldShowWeekdaysOut() is set to true, selecting a date not from the current month scrolls the calendar to the previous or next month. And the 1st is selected like @bjaskj Missbehaviour 1. 

Would be great if you could stop this behaviour so highlight the date selected without scrolling the calendar. Even with the scrolling, highlighting the correct date that was selected instead of the 1st perhaps is an easy update/fix!

**Comment by ridvank** [comment]
Is there any update on this issue?

**Comment by shan199105** [comment]
I have pretty much the same problem. Any updates?
