### ISSUE TITLE
Prevent Auto selection of day when swiping through months

### ISSUE THREAD

**Issue by rmickeyd** [CVCalendar/CVCalendar#253]
I am segueing back to the ViewController that launched the CalendarView.  It chooses what day to segue based on what day is selected.  However, when I swipe to a new month it auto selects the first day of the month and segues to that day.

How do I prevent the 1st of the month from auto selecting when I swipe to a new month?

**Comment by pavelhiq** [comment]
Take a look at shouldAutoSelectDayOnMonthChange() method of the CVCalendarViewDelegate delegate

**Comment by pavelhiq** [comment]
For me it is the other side of the problem: if I switch this off I cannot make the calendar select some predefined date from the beginning, the selection remains empty after a toggleViewWithDate(someDate) call. Any ideas?

**Comment by rmickeyd** [comment]
Just off the top of my head.. could you do something like 
predefinedDate = CVDate?()

then in didSelectDayView check if its nil.  If it is nil then it will auto select today and first of month, if its not then go to the date stored (maybe this does not work if you cycle through months).  You could apply same conditional to shouldAutoSelectDayOnMonthChange if needed.

Not 100% this would work, I do not have Xcode in front of me right now.

**Comment by danielbmarques** [comment]
@pavelhiq Did you get anywhere on this? I'm having the same problem, and @rmickeyd's suggestion didn't work.

**Comment by pavelhiq** [comment]
I ended up with somewhat "acceptable" for the moment and do like this:

- let _shouldAutoSelectDayOnMonthChange()_ return true, automatic selection will happen
- at start the selected view is empty (_null_) -- can live with that so if I return from the calendar view that means user has not selected anything, but Today is still highlighted in the calendar view though
- dont use custom date selection at start since it seems to be only possible along with automatic selection and has some ugly graphic 'jumps'
- _toggleViewWithDate(someDate)_ does not work if you dont have some day explicitly selected, therefore Today functionality will not work at start -- so I added a workaround to capture such actions and check it if user leaves the calendar vc

that's it, though Id like this nice library to dictate less about use cases...

**Comment by danielbmarques** [comment]
@pavelhiq Thanks for the answer. I'll see if I can do something about this when I have the time.

**Comment by Havusoft** [comment]
CVCalendarMonthContentViewController.swift
Comment these lines
`if matchedMonths(current, presented)
 {
          //selectDayViewWithDay(current.day, inMonthView: presentedMonthView)               
 }
 else 
 {
           //selectDayViewWithDay(CVDate(date: calendarView.manager
                   //.monthDateRange(presentedMonthView.date).monthStartDate, calendar: calendar).day,
                                         //inMonthView: presentedMonthView)
 }`
